dbt_spark_demo:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: test
      host: localhost
      # optional
      port: 10000              # default 10001
#      user: [ user ]
#      auth: [ e.g. KERBEROS ]
#      kerberos_service_name: [ e.g. hive ]

